export const UPDATE_BACKGROUND = 'UPDATE_BACKGROUND';
export const UPDATE_TEXT = 'UPDATE_TEXT';
export const UPDATE_SIZE = 'UPDATE_SIZE';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_FONT = 'UPDATE_FONT';
